service: refactor-auth

plugins:
  - serverless-webpack

provider:
  deploymentBucket:
    name: ${file(../../config.yml):deploymentBucket, 'refactor-deployment'}
  name: aws
  runtime: nodejs8.10
  region: ${opt:region, 'us-west-2'}

package:
  individually: true

functions:
  pre_signup:
    handler: functions/pre_signup/index.handler
    role: PreSignupRole
    events:
      - cognitoUserPool:
          pool: MyUserPool
          trigger: PreSignUp
    environment:
      TABLE_REFACTOR: ${cf:refactor-db-${self:custom.stage}.DynamoTableRefactor}

custom:
  stage: ${opt:stage}

resources:
  - ${file(resources/cognito.yml)}
  - ${file(resources/iam.yml)}
