version: 2

jobs:
  build:
    docker:
      - image: rolme/refactor-image-circleci
        auth:
          username: rolme
          password: $DOCKERHUB_PASSWORD

    working_directory: ~/repo

    branches:
      only:
        - master
        - ci

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-yarn-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-yarn-

      - run:
          name: Install serverless and dependencies
          command: yarn

      - save_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules
            - services/auth/node_modules
            - services/db/node_modules
            - services/graph/node_modules
            - services/media/node_modules
            - services/storage/node_modules
            - tests/node_modules

      - run:
          name: Deploy services (circleci)
          command: yarn run deploy -s circleci -v

      - run:
          name: Export to S3 (circleci)
          command: |
            aws s3 cp exports.yml s3://refactor-deployment/exports/circleci/exports.yml

      - run:
          name: Regression tests (circleci)
          command: yarn run test

      - run:
          name: Deploy services (staging)
          command: yarn run deploy -s staging -v

      - run:
          name: Export to S3 (staging)
          command: |
            aws s3 sync awsconfig s3://refactor-deployment/exports/staging/awsconfig --acl bucket-owner-full-control
            aws s3 sync amplify s3://refactor-deployment/exports/staging/amplify --acl bucket-owner-full-control
            aws s3 cp exports.yml s3://refactor-deployment/exports/staging/exports.yml --acl bucket-owner-full-control
