Resources:
  DynamoTableAtomicVars:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:service}-${self:custom.stage}-AtomicVars
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: varName
          AttributeType: S
      KeySchema:
        - AttributeName: varName
          KeyType: HASH

  DynamoTableRefactor:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:service}-${self:custom.stage}-Refactor
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: hash
          AttributeType: S
        - AttributeName: range
          AttributeType: S
        - AttributeName: type
          AttributeType: S
        - AttributeName: scope
          AttributeType: S
      KeySchema:
        - AttributeName: hash
          KeyType: HASH
        - AttributeName: range
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: RangeHashIndex
          KeySchema:
            - AttributeName: range
              KeyType: HASH
            - AttributeName: hash
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: TypeScopeIndex
          KeySchema:
            - AttributeName: type
              KeyType: HASH
            - AttributeName: scope
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

Outputs:
  DynamoTableAtomicVars:
    Value:
      Ref: DynamoTableAtomicVars
  DynamoTableRefactor:
    Value:
      Ref: DynamoTableRefactor
