Resources:
  DynamoTableRefactor:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:service}-${self:custom.stage}-Refactor
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: key
          AttributeType: S
        - AttributeName: entity
          AttributeType: S
        - AttributeName: scope
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: N
        - AttributeName: updatedAt
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: key
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: KeyIdIndex
          KeySchema:
            - AttributeName: key
              KeyType: HASH
            - AttributeName: id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: EntityIdIndex
          KeySchema:
            - AttributeName: entity
              KeyType: HASH
            - AttributeName: id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: entityCreatedAtIndex
          KeySchema:
            - AttributeName: entity
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: entityUpdatedAtIndex
          KeySchema:
            - AttributeName: entity
              KeyType: HASH
            - AttributeName: updatedAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: EntityScopeIndex
          KeySchema:
            - AttributeName: entity
              KeyType: HASH
            - AttributeName: scope
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

Outputs:
  DynamoTableRefactor:
    Value:
      Ref: DynamoTableRefactor
