Resources:
  DynamoTableRefactor:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:service}-${self:custom.stage}-Refactor
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: sort
          AttributeType: S
        - AttributeName: data
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: sort
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: gsi1pk
          KeySchema:
            - AttributeName: sort
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: gsi1sk
          KeySchema:
            - AttributeName: data
              KeyType: HASH
          Projection:
            ProjectionType: ALL

Outputs:
  DynamoTableRefactor:
    Value:
      Ref: DynamoTableRefactor
