service: refactor-storage

provider:
  deploymentBucket:
    name: ${file(../../config.yml):deploymentBucket, 'refactor-deployment'}
  name: aws
  region: ${opt:region, 'us-west-2'}

custom:
  stage: ${opt:stage}

resources:
  - ${file(resources/s3.yml)}
